apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: digicel/user-data
      context: user-data
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
<<<<<<< HEAD
    # - image: digicel/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "**/*.js"
    #         dest: .
=======
    - image: digicel/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
>>>>>>> 324282cfe58ecca331acee4d034656e641fd3275
    - image: digicel/transactions
      context: transactions
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: digicel/accounts
      context: accounts
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: digicel/product
    #   context: product
    #   docker:
    #     dockerfile: DockerFile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: digicel/accounts
    #   context: accounts
    #   docker:
    #     dockerfile: DockerFile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: digicel/notifications
      context: notifications
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: digicel/expiration
      context: expiration
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: digicel/notifications
      context: notifications
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: digicel/cash
      context: cash
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
