apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: digicel/auth:latest
          env:
            - name: AWS_BUCKET_NAME
              value: ''
            - name: AWS_BUCKET_REGION
              value: ''
            - name: ACCESS_KEY_ID
              value: ''
            - name: AWS_SECRET_ACCESS_KEY
              value: ''
            - name: TWILIO_ACCOUNT_SID
              value: ''
            - name: TWILIO_AUTH_TOKEN
              value: ''
            - name: ONFIDO_API_TOKEN
              value: ''
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
