apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: digicel/auth:latest
          env:
            - name: AWS_BUCKET_NAME
              value: 'digicell-bucket'
            - name: AWS_BUCKET_REGION
              value: 'ap-southeast-1'
            - name: ACCESS_KEY_ID
              value: 'AKIARJ5OYBXGRVHTQM6W'
            - name: AWS_SECRET_ACCESS_KEY
              value: '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'
            - name: TWILIO_ACCOUNT_SID
              value: ''
            - name: TWILIO_AUTH_TOKEN
              value: ''
            - name: ONFIDO_API_TOKEN
              value: 'api_sandbox_us.5KyZsPeogLb.dPJI2tWP_LxvWExZ8XqkrM5JDfmd0Jju'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: digicel
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
